FROM node:22-slim

ARG PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_NAME
ARG EXTERNAL_DB_NAME
ARG RABBITMQ_IP
ARG RABBITMQ_PORT
ARG RABBITMQ_USERNAME
ARG RABBITMQ_PASSWORD
ARG ACTIVE_MERCHANTS
ARG MAILS_QUEUE



ENV PORT=$PORT
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_HOST=$DB_HOST
ENV DB_NAME=$DB_NAME
ENV EXTERNAL_DB_NAME=$EXTERNAL_DB_NAME
ENV RABBITMQ_IP=$RABBITMQ_IP
ENV RABBITMQ_PORT=$RABBITMQ_PORT
ENV RABBITMQ_USERNAME=$RABBITMQ_USERNAME
ENV RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
ENV ACTIVE_MERCHANTS=$ACTIVE_MERCHANTS
ENV MAILS_QUEUE=$MAILS_QUEUE


WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm install -g typescript

RUN tsc

EXPOSE 4000

CMD ["npm", "run", "start"]
